# frozen_string_literal: true

source("https://rubygems.org")
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in yiffspace-search.gemspec.
gemspec

gem("yiffspace-core", path: "../yiffspace-core")
gem("yiffspace-ext", path: "../yiffspace-ext")
gem("yiffspace-user", path: "../yiffspace-user")

group(:development) do
  gem("rubocop", "~> 1.86", require: false)
  gem("rubocop-erb", "~> 0.7.1", require: false)
  gem("rubocop-rails", "~> 2.34", require: false)
  gem("rubocop-yiffspace", "~> 0.0.1", require: false)
end
