name: RuboCop

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  rubocop:
    strategy:
      matrix:
        dir: [ yiffspace, yiffspace-arel, yiffspace-auth, yiffspace-config, yiffspace-core, yiffspace-ext, yiffspace-fixers, yiffspace-images, yiffspace-include, yiffspace-search, yiffspace-tables, yiffspace-user ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.dir }}/.ruby-version
          bundler-cache: true
          working-directory: ${{ matrix.dir }}
      - run: bundle exec rubocop
        working-directory: ${{ matrix.dir }}
