name: Zeitwerk

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  zeitwerk:
    strategy:
      matrix:
        include:
          - dir: yiffspace
            require: yiffspace
          - dir: yiffspace-auth
            require: yiffspace/auth
          - dir: yiffspace-fixers
            require: yiffspace/fixers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.dir }}/.ruby-version
          bundler-cache: true
          working-directory: ${{ matrix.dir }}
      - run: bundle exec ruby -e "require('${{ matrix.require }}'); Zeitwerk::Loader.eager_load_all"
        working-directory: ${{ matrix.dir }}
