name: Zeitwerk

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  zeitwerk:
    strategy:
      matrix:
        include:
          - dir: yiffspace
            require: yiffspace
          - dir: yiffspace-arel
            require: yiffspace/arel
          - dir: yiffspace-auth
            require: yiffspace/auth
          - dir: yiffspace-config
            require: yiffspace/config
          - dir: yiffspace-core
            require: yiffspace/core
          - dir: yiffspace-ext
            require: yiffspace/ext
          - dir: yiffspace-fixers
            require: yiffspace/fixers
          - dir: yiffspace-images
            require: yiffspace/images
          #- dir: yiffspace-include
          #  require: yiffspace/include
          - dir: yiffspace-search
            require: yiffspace/search
          - dir: yiffspace-tables
            require: yiffspace/tables
          - dir: yiffspace-user
            require: yiffspace/user
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: packages/${{ matrix.dir }}
      - run: bundle exec ruby -e "require('${{ matrix.require }}'); Zeitwerk::Loader.eager_load_all"
        working-directory: packages/${{ matrix.dir }}
